- name: Update package cache
  pacman:
    update_cache: yes

- name: Install deps
  pacman:
    name: "{{item}}"
    state: present
  with_items:
    - base-devel
    - libexif
    - libjpeg-turbo

- name: Sets vars for gphoto2 path
  set_fact:
    libgphoto2_src: "{{source_dir}}/libgphoto2-{{version or 'latest'}}"
    libgphoto2_build: "{{build_dir}}/libgphoto2"

- name: Download libgphoto2-{{version or 'latest'}}
  git:
    repo: https://github.com/gphoto/libgphoto2.git
    clone: yes
    update: yes
    force: yes
    version: "{{version or HEAD}}"
    dest: "{{libgphoto2_src}}"

- name: Remove build dir
  file:
    state: absent
    path: "{{libgphoto2_build}}/"

- name: Create build dir
  file:
    path: "{{libgphoto2_build}}"
    state: directory

- name: Copy gphoto2 to build dir
  command: "rsync -a {{libgphoto2_src}}/ {{libgphoto2_build}}"

- name: Build libgphoto2
  shell: >
    cd "{{libgphoto2_build}}" &&
    autoreconf --install --symlink &&
    ./configure --prefix /usr &&
    make -j2 &&
    make install
  args:
    creates: "/usr/lib/libgphoto2.so"
