- name: Set units for spc-eyepi
  set_fact:
    systemd_units:
      - {unit: "eyepi-capture.service",       enable: yes,  restart: yes}
      - {unit: "reboot_daily.timer",          enable: yes,  restart: yes}
      - {unit: "reboot_daily.service",        enable: no,   restart: no}
      - {unit: "eyepi-api.service",           enable: yes,  restart: no}
      - {unit: "eyepi-webinterface.service",  enable: yes,  restart: no}

- name: Download gphoto2-cffi
  git:
    repo: https://github.com/borevitzlab/gphoto-cffi.git
    clone: yes
    update: yes
    force: yes
    version: "HEAD"
    dest: "{{home_dir}}/gphoto2-cffi"

- name: Download spc-eyepi
  git:
    repo: https://github.com/borevitzlab/spc-eyepi.git
    clone: yes
    update: yes
    force: yes
    version: "HEAD"
    dest: "{{home_dir}}/spc-eyepi"

- name: Create Directories for spc-eyepi
  file:
    dest: "{{home_dir}}/{{item}}"
    state: directory
    group: users
    mode: 0775
  with_items:
    - "spc-eyepi"
    - "spc-eyepi/configs_byserial"
    - "images"

- name: Copy systemd units
  copy:
    remote_src: yes
    src: "{{home_dir}}/spc-eyepi/{{item.unit}}"
    dest: "/etc/systemd/system/{{item.unit}}"
  with_items:
    - "{{systemd_units}}"

- name: Restart and Enable spc-eyepi systemd units
  systemd:
    name: "{{item}}"
    state: "{{'restarted' if unit.restart else 'started'}}"
    enabled: "{{True if unit.enabled else False}}"
    masked: no
  with_items:
    - "{{systemd_units}}"
