- name: Install OpenVPN
  pacman:
    update_cache: yes
    name: openvpn
    state: present

- name: "check local for {{vpn_config_file}}"
  local_action: stat path="{{vpn_config_file}}"
  register: ovpn_conf


- name: "check local for vpn login.conf"
  stat:
    path: "/etc/openvpn/client/login.conf"
  register: ovpn_login

- debug: msg="OpenVPN configuration file exists, using {{vpn_config_file}}"
  when: ovpn_conf.stat.exists

- debug: msg="OpenVPN configuration file doesnt exist... {{vpn_config_file}}"
  when: not ovpn_conf.stat.exists

- name: Ensure /etc/openvpn/client dir exists
  file: path=/etc/openvpn/client state=directory

- name: Install openvpn conf
  copy:
    src: "{{vpn_config_file}}"
    dest: "/etc/openvpn/client/vpn.conf"
  when: ovpn_conf.stat.exists

- name: Start openvpn systemd service
  systemd:
    name: openvpn-client@vpn
    state: started
    daemon_reload: yes
    enabled: yes
    masked: no
  when: ovpn_conf.stat.exists and ovpn_login.stat.exists
