- name: Add sftp.traitcapture.org to global known hosts
  lineinfile:
    create: yes
    state: present
    line: "sftp.traitcapture.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDA0sQQQX5oUhD8IJ5p1hgnHqGJSTW8faO68xYrVJwa0u9nXTYJzccK3YoyOBjfflp7dldL6cRO8DWhTfN8TyM8="
    regexp: "^.*sftp.traitcapture.org.*"
    dest: /etc/ssh/ssh_known_hosts

- file:
    path: /etc/ssh/ssh_known_hosts
    state: file
    mode: 755
    owner: root

- name: Add sftp.traitcapture.org to known hosts for root (just to be safe)
  lineinfile:
    create: yes
    state: present
    line: "sftp.traitcapture.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNCe/FWooJca3g/YcOFNtIrph1HC0DlGaJM5cFzkrb/eeGe9OFQUmLTaR3bfAexaeXMqGTC1KxtS/mhOb/I4ZZs="
    regexp: "^.*sftp.traitcapture.org.*"
    dest: /home/.ssh/known_hosts

- file:
    path: /home/.ssh
    owner: root
    state: directory
    mode: 700

- name: Get a new ssh key from the server.
  uri:
    url: "https://traitcapture.org/api/v3/remote/by-machine/{{ansible_machine_id}}?token={{api_key}}"
    method: POST
    body: "hostname={{inventory_hostname}}&token={{api_key}}"
    return_content: yes
  register: sshkey
  when: api_key is defined

- copy:
    content: "{{(sshkey.content|from_json)['id_rsa']}}"
    dest: /home/.ssh/id_rsa
  when: sshkey.content is defined and sshkey.content|from_json is defined

- copy:
    content: "{{(sshkey.content|from_json)['id_rsa.pub']}}"
    dest: /home/.ssh/id_rsa.pub
  when: sshkey.content is defined and sshkey.content|from_json is defined

- stat:
    path: /home/.ssh/id_rsa
  register: stat_id_rsa

- stat:
    path: /home/.ssh/id_rsa.pub
  register: stat_id_rsa_pub

- file:
    path: /home/.ssh/id_rsa
    state: file
    mode: 600
    owner: root
  when: stat_id_rsa.stat.exists
