- hosts: all
  vars_files:
    - vars/misc.yml
    - vars/userlist.yml
    - vars/pkgs.yml
    - vars/hostmap.yml
    - secure/wireless_networks.yml

  vars:
    - host_locale: en_AU.UTF-8
    - host_locale_dict: {
            LANG: "{{ host_locale }}",
            LC_COLLATE: "{{ host_locale }}",
            LC_CTYPE: "{{ host_locale }}",
            LC_MESSAGES: "{{ host_locale }}",
            LC_MONETARY: "{{ host_locale }}",
            LC_NUMERIC: "{{ host_locale }}",
            LC_TIME: "{{ host_locale }}",
            LC_ALL: "{{ host_locale }}"
        }

  tasks:
    - include: tasks/base_setup.yml
      tags: base,setup, always

    - include: tasks/rpi_config.yml
      tags: base,setup

    - include: tasks/users.yml
      tags: base,users

    - include: tasks/sftp_key.yml
      tags: network,sftp

    - include: tasks/updatepkgs.yml
      tags: base

    - include: tasks/installpkgs.yml suite="Base" pkgs="{{packages_base}}"
      tags: pkgs,base

    - include: tasks/installpkgs.yml suite="Eyepi" pkgs="{{pacman_pkgs}}"
      tags: pkgs,dist

    - include: tasks/openvpn.yml vpn_config_file="{{vpn_conf}}"
      tags: network

    - include: tasks/tor.yml
      tags: network

    - include: tasks/wireless.yml interface="wlan0"
      tags: network,wireless
      when: wireless_keys is defined


    - include: software_modules/butterfly.yml
      tags: network,shell

    - include: software_modules/gphoto2.yml version=HEAD
      tags: modules,gphoto2
      when: build_gphoto2 is defined and build_gphoto2 == True

    - include: tasks/installpkgs.yml suite="gphoto2/libgphoto2" pkgs="libgphoto2 gphoto2"
      tags: modules,gphoto2
      when: build_gphoto2 is not defined or build_gphoto2 == False

    - include: tasks/python_modules.yml modules="{{python_pkgs}}"
      tags: pkgs,python

    - include: software_modules/telegraf.yml
      tags: telegraf,metrics

    - include: software_modules/spc-eyepi.yml
      tags: modules,eyepi
